(function(){
  'use strict';
  const ENERGY_KEY='tanida_energy_v1';
  const defaults={solarKW:110,solarHours:7,solarEfficiency:85,solarCoverage:60,pumpKW:0,electricityEnabled:false,gridKW:0,gridHours:0,tariff:0,tariffEsc:5,electricityAvailability:100,solarCapex:0,solarOM:2};
  const E=(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(ENERGY_KEY)||'{}')}}catch(e){return {...defaults}}})();
  const q=id=>document.getElementById(id), n=v=>Number(v||0), f=x=>Number(x||0).toLocaleString('ar-EG-u-nu-arab',{maximumFractionDigits:0}), money=x=>f(x)+' ج', pct=x=>f(x)+'٪';
  function saveE(){localStorage.setItem(ENERGY_KEY,JSON.stringify(E));}
  function addEnergyUI(){const sec=q('water');if(!sec||q('energyAdvancedCard'))return;const card=document.createElement('div');card.className='card';card.id='energyAdvancedCard';card.innerHTML=`<h3>إعدادات الطاقة الشمسية والكهرباء — مرتبطة بالمحرك المالي</h3><div class="callout"><b>مهم:</b> هذه المدخلات تحدد تكلفة ومخاطر الطاقة في Forecast 2026–2048. لا يختلق النظام تكلفة كهرباء إذا لم تُفعّل الكهرباء؛ ولا يعتبر kW الشمسي وحده دليلًا على كفاية تشغيل المضخة.</div><div class="grid g4" style="margin-top:12px"><div class="field"><label>قدرة الألواح الشمسية kW</label><input id="enSolarKW" type="number" step=".1"></div><div class="field"><label>ساعات الشمس الفعلية/يوم</label><input id="enSolarHours" type="number" step=".1"></div><div class="field"><label>كفاءة النظام الشمسي %</label><input id="enSolarEfficiency" type="number" step=".1"></div><div class="field"><label>نسبة تغطية الشمس للحمل %</label><input id="enSolarCoverage" type="number" step=".1"></div><div class="field"><label>قدرة المضخة الفعلية kW</label><input id="enPumpKW" type="number" step=".1" placeholder="أدخل من لوحة المضخة"></div><div class="field"><label>هل توجد كهرباء للمزرعة؟</label><select id="enElectricity"><option value="0">لا</option><option value="1">نعم</option></select></div><div class="field"><label>القدرة الكهربائية المتاحة kW</label><input id="enGridKW" type="number" step=".1"></div><div class="field"><label>ساعات الكهرباء المتاحة/يوم</label><input id="enGridHours" type="number" step=".1"></div><div class="field"><label>تعرفة الكهرباء ج/ك.و.س</label><input id="enTariff" type="number" step=".01"></div><div class="field"><label>زيادة التعرفة السنوية %</label><input id="enTariffEsc" type="number" step=".1"></div><div class="field"><label>توافر الشبكة %</label><input id="enAvailability" type="number" step=".1"></div><div class="field"><label>Capex النظام الشمسي</label><input id="enSolarCapex" type="number"></div><div class="field"><label>صيانة الشمس % من Capex/سنة</label><input id="enSolarOM" type="number" step=".1"></div></div><div class="controls no-print" style="margin-top:12px"><button class="btn" id="saveEnergyBtn">حفظ وتحليل الطاقة</button><button class="btn secondary" id="clearEnergyBtn">إعادة القيم الأساسية</button></div><div id="energyAdvancedResult" style="margin-top:14px"></div>`;sec.appendChild(card);fillEnergy();q('saveEnergyBtn').onclick=saveEnergyInputs;q('clearEnergyBtn').onclick=()=>{Object.assign(E,defaults);saveE();fillEnergy();renderEnergy();renderAllWithEnergy();};renderEnergy();}
  function fillEnergy(){['solarKW','solarHours','solarEfficiency','solarCoverage','pumpKW','gridKW','gridHours','tariff','tariffEsc','electricityAvailability','solarCapex','solarOM'].forEach(k=>{const id='en'+k.charAt(0).toUpperCase()+k.slice(1);if(q(id))q(id).value=E[k]});if(q('enElectricity'))q('enElectricity').value=E.electricityEnabled?'1':'0';}
  function saveEnergyInputs(){['solarKW','solarHours','solarEfficiency','solarCoverage','pumpKW','gridKW','gridHours','tariff','tariffEsc','electricityAvailability','solarCapex','solarOM'].forEach(k=>{const id='en'+k.charAt(0).toUpperCase()+k.slice(1);if(q(id))E[k]=n(q(id).value)});E.electricityEnabled=q('enElectricity')?.value==='1';saveE();renderEnergy();renderAllWithEnergy();alert('تم حفظ إعدادات الطاقة وربطها بالحسابات.');}
  function energyCalc(yearIndex=0){const days=n(q('wellDays')?.value)||365,hours=n(q('wellHours')?.value)||7,pump=n(E.pumpKW),annualLoad=pump*hours*days,solarProduced=n(E.solarKW)*n(E.solarHours)*days*(n(E.solarEfficiency)/100),solarUsed=Math.min(annualLoad,solarProduced,annualLoad*n(E.solarCoverage)/100),residual=Math.max(0,annualLoad-solarUsed),avail=n(E.electricityAvailability)/100,gridCap=n(E.gridKW)*n(E.gridHours)*days*avail,gridKwh=E.electricityEnabled?Math.min(residual,gridCap||residual):0,unmet=Math.max(0,residual-gridKwh),tariff=n(E.tariff)*Math.pow(1+n(E.tariffEsc)/100,yearIndex),gridCost=gridKwh*tariff,om=n(E.solarCapex)*n(E.solarOM)/100*Math.pow(1+n(q('fcCostEsc')?.value||5)/100,yearIndex);return {annualLoad,solarProduced,solarUsed,residual,gridCap,gridKwh,unmet,tariff,gridCost,om,totalEnergyCost:gridCost+om};}
  function renderEnergy(){const r=energyCalc(0),el=q('energyAdvancedResult');if(!el)return;const status=r.unmet>0?'bad':(E.electricityEnabled?'good':'info');el.innerHTML=`<div class="grid g4"><div class="kpi"><div class="l">حمل المضخة السنوي</div><div class="v">${f(r.annualLoad)} ك.و.س</div><div class="n">قدرة المضخة × ساعات التشغيل × الأيام</div></div><div class="kpi"><div class="l">إنتاج الشمس النظري</div><div class="v">${f(r.solarProduced)} ك.و.س</div><div class="n">مع الكفاءة المدخلة</div></div><div class="kpi"><div class="l">استهلاك الشبكة المتوقع</div><div class="v">${f(r.gridKwh)} ك.و.س</div><div class="n">بعد مساهمة الشمس</div></div><div class="kpi"><div class="l">تكلفة الطاقة السنوية</div><div class="v">${money(r.totalEnergyCost)}</div><div class="n">كهرباء + صيانة شمسية</div></div></div><div class="callout ${status==='bad'?'warn':''}" style="margin-top:12px"><b>${r.unmet>0?'يوجد عجز طاقة يحتاج معالجة':'لا يوجد عجز طاقة حسابي وفق المدخلات'}</b><br>الشمس تغطي ${pct(r.annualLoad?100*r.solarUsed/r.annualLoad:0)} من حمل المضخة، والشبكة تغطي ${pct(r.annualLoad?100*r.gridKwh/r.annualLoad:0)}، والعجز ${f(r.unmet)} ك.و.س/سنة. ${E.electricityEnabled?'تعرفة السنة الأولى: '+money(E.tariff)+' لكل ك.و.س.':'الكهرباء غير مفعلة؛ أي عجز متبقٍ لا يتحول تلقائيًا إلى تكلفة كهرباء.'}</div>`;}
  const originalBuildForecast=window.buildForecast;window.buildForecast=function(scenarioKey){const r=originalBuildForecast(scenarioKey),f=r.f||{},solarCapex=n(E.solarCapex);let energyCostTotal=0;(r.years||[]).forEach((y,i)=>{const e=energyCalc(i);y.energyCost=e.totalEnergyCost;y.net-=e.totalEnergyCost;y.cum-=e.totalEnergyCost;energyCostTotal+=e.totalEnergyCost;});if(solarCapex>0){r.openingCharge+=solarCapex;r.flows[0]-=solarCapex;}r.totalCost+=energyCostTotal+solarCapex;r.totalNet-=energyCostTotal+solarCapex;r.npv=window.npv(f.discount,r.flows);r.irr=window.irr(r.flows);r.roi=r.openingCharge>0?(r.totalNet-r.openingCharge)/r.openingCharge:null;return r;};
  function patchForecastTable(){const t=q('forecastRows');if(!t)return;const table=t.closest('table');const head=table?.querySelector('thead tr');if(head&&!head.querySelector('.energy-head')){const th=document.createElement('th');th.className='energy-head';th.textContent='الطاقة';head.insertBefore(th,head.lastElementChild)}[...t.querySelectorAll('tr')].forEach((tr,i)=>{const cells=tr.querySelectorAll('td');if(!cells.length)return;const td=document.createElement('td');td.textContent=money(energyCalc(i).totalEnergyCost);tr.insertBefore(td,cells[cells.length-1]);});}
  function renderAllWithEnergy(){try{if(typeof window.render==='function')window.render();}catch(e){}setTimeout(()=>{try{renderEnergy();patchForecastTable();}catch(e){}},0);}
  const oldRenderWater=window.renderWater;if(typeof oldRenderWater==='function')window.renderWater=function(c){try{oldRenderWater(c)}catch(e){}renderEnergy();};
  const oldDecisionAnalysis=window.decisionAnalysis;if(typeof oldDecisionAnalysis==='function')window.decisionAnalysis=function(c,rf){const arr=oldDecisionAnalysis(c,rf)||[],e=energyCalc(0);if(e.unmet>0)arr.push({type:'blocker',title:'عجز الطاقة',text:`يوجد عجز طاقة حسابي ${f(e.unmet)} ك.و.س/سنة. لا توسع حمل البئر قبل توفير مصدر طاقة كافٍ.`});else arr.push({type:'ok',title:'الطاقة',text:`تكلفة الطاقة السنوية المحسوبة ${money(e.totalEnergyCost)} وفق المدخلات الحالية.`});return arr;};
  const oldStable=window.stableAIData;if(typeof oldStable==='function')window.stableAIData=function(){const x=oldStable();x.inputs.energyAdvanced={...E,calculation:energyCalc(0)};return x;};
  addEnergyUI();const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();setTimeout(()=>{fillEnergy();renderEnergy();patchForecastTable();},0)};setTimeout(()=>{try{renderAllWithEnergy()}catch(e){}},50);
})();
