/* V11.0 — Professional Interactive Tanida Farm Plan
   Visual layer = schematic only. All quantities remain live and come from the farm state/calculation layer. */
(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s);
const FARM_LOCATION={lat:25.4026389,lng:29.4066667,latDms:'25°24\'09.5"N',lngDms:'29°24\'24.0"E'};
const nf=new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0});
const state=()=>{try{return JSON.parse(localStorage.getItem('tanida_dashboard_v2')||'{}')}catch(e){return {}}};
const n=v=>Number(v||0);
const fmt=v=>nf.format(n(v));
function inject(){if($('#farmMapProStyle'))return;const st=document.createElement('style');st.id='farmMapProStyle';st.textContent=`
@import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;600;700;800;900&display=swap');
.farm-map-pro{position:relative;min-height:700px;border:1px solid #d9e2dc;border-radius:22px;overflow:hidden;background:#ead8b9;box-shadow:0 10px 28px rgba(17,38,29,.10);font-family:Cairo,Tahoma,sans-serif;direction:rtl}
.farm-map-pro .fmp-bg{position:absolute;inset:0;background:radial-gradient(circle at 18% 12%,rgba(255,255,255,.28),transparent 26%),linear-gradient(135deg,#e9d8b8,#d5bb8d 52%,#c7aa75);}
.farm-map-pro .fmp-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.10) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.10) 1px,transparent 1px);background-size:48px 48px;opacity:.45}
.fmp-title{position:absolute;top:16px;right:16px;z-index:12;background:rgba(255,255,255,.94);border:1px solid #d5ded8;border-radius:14px;padding:9px 14px;box-shadow:0 5px 16px #0002;color:#174b3a}.fmp-title b{display:block;font-size:15px}.fmp-title span{font-size:10px;color:#69766f}
.fmp-north{position:absolute;top:18px;left:18px;z-index:12;width:55px;height:68px;text-align:center;color:#174b3a;font-weight:900}.fmp-north .arrow{width:0;height:0;margin:auto;border-left:18px solid transparent;border-right:18px solid transparent;border-bottom:44px solid #174b3a;filter:drop-shadow(0 3px 3px #0003)}.fmp-north small{font-size:9px}
.fmp-svg{position:absolute;inset:78px 8% 22px 8%;width:84%;height:calc(100% - 100px);overflow:visible;filter:drop-shadow(0 14px 18px rgba(69,51,22,.18))}
.fmp-land{fill:#e7e0cf;stroke:#fff;stroke-width:4}.fmp-sector{stroke:#fff;stroke-width:4;cursor:pointer;transition:.18s;filter:drop-shadow(0 2px 3px #0002)}.fmp-sector:hover,.fmp-sector.active{stroke:#174b3a;stroke-width:6;filter:drop-shadow(0 7px 10px #0004);opacity:.96}
.fmp-wheat{fill:#d9aa2f}.fmp-alfalfa{fill:#4d9b57}.fmp-expand{fill:#b9b3a0}.fmp-service{fill:#8d789b}.fmp-water{fill:#d2c7b0}.fmp-power{fill:#a99465}
.fmp-road{fill:#555b58;stroke:#eee7d5;stroke-width:7}.fmp-road2{fill:none;stroke:#666b67;stroke-width:10;stroke-linecap:round}.fmp-road2+path{stroke:#f0eadc;stroke-width:2;fill:none}
.fmp-label{font-family:Cairo,Tahoma,sans-serif;font-weight:800;fill:#fff;text-anchor:middle;paint-order:stroke;stroke:#3b3b2f;stroke-width:4px;stroke-linejoin:round}.fmp-label.dark{fill:#24352c;stroke:#fff;stroke-width:3px}.fmp-label .big{font-size:18px}.fmp-label .small{font-size:11px;font-weight:600}.fmp-label .area{font-size:15px}
.fmp-point{fill:#fff;stroke:#0f6b55;stroke-width:5;cursor:pointer}.fmp-point-core{fill:#0f6b55}.fmp-point-text{font-family:Cairo,Tahoma,sans-serif;font-size:12px;font-weight:800;fill:#174b3a;text-anchor:middle;paint-order:stroke;stroke:#fff;stroke-width:5px}
.fmp-live{position:absolute;left:16px;bottom:16px;z-index:20;width:300px;background:rgba(255,255,255,.96);border:1px solid #d7e0da;border-radius:16px;padding:13px;box-shadow:0 9px 25px #0003}.fmp-live h4{margin:0 0 8px;color:#174b3a;font-size:14px}.fmp-live-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.fmp-live-item{background:#f5f8f6;border-radius:10px;padding:7px 9px}.fmp-live-item span{display:block;color:#6c7871;font-size:9px}.fmp-live-item b{display:block;color:#174b3a;font-size:15px}.fmp-live-note{font-size:9px;color:#68756d;margin-top:8px;line-height:1.7}.fmp-detail{position:absolute;right:16px;bottom:16px;z-index:20;width:315px;background:rgba(255,255,255,.96);border:1px solid #d7e0da;border-radius:16px;padding:13px;box-shadow:0 9px 25px #0003}.fmp-detail h4{margin:0;color:#174b3a;font-size:14px}.fmp-detail p{font-size:10px;color:#647169;line-height:1.8;margin:5px 0}.fmp-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.fmp-detail-grid div{background:#f5f8f6;border-radius:9px;padding:6px}.fmp-detail-grid span{display:block;font-size:8px;color:#77827c}.fmp-detail-grid b{font-size:12px;color:#174b3a}.fmp-btn{display:inline-flex;border:0;border-radius:9px;background:#0f795b;color:#fff;padding:7px 10px;text-decoration:none;font:700 10px Cairo;cursor:pointer;margin-top:7px}.fmp-legend{position:absolute;top:86px;left:16px;z-index:15;background:rgba(255,255,255,.93);border:1px solid #d7e0da;border-radius:13px;padding:9px;width:155px;box-shadow:0 5px 15px #0002}.fmp-legend h5{margin:0 0 6px;color:#174b3a;font-size:11px}.fmp-legend-row{display:flex;align-items:center;gap:6px;font-size:9px;color:#4e5d55;margin:4px 0}.fmp-swatch{width:15px;height:15px;border-radius:4px;border:1px solid #fff;box-shadow:0 1px 2px #0002}.sw-wheat{background:#d9aa2f}.sw-alf{background:#4d9b57}.sw-exp{background:#b9b3a0}.sw-serv{background:#8d789b}.sw-water{background:#d2c7b0}.sw-power{background:#a99465}
.fmp-coord{position:absolute;top:86px;right:16px;z-index:15;background:rgba(23,75,58,.94);color:#fff;border-radius:11px;padding:7px 10px;font-size:9px;box-shadow:0 5px 15px #0003}.fmp-coord a{display:block;color:#f4d77c;text-decoration:none;font-weight:800;margin-top:3px}
@media(max-width:900px){.farm-map-pro{min-height:620px}.fmp-svg{inset:90px 4% 170px 4%;width:92%;height:calc(100% - 260px)}.fmp-live,.fmp-detail{width:calc(50% - 25px);bottom:12px}.fmp-live{left:12px}.fmp-detail{right:12px}.fmp-legend{top:auto;bottom:165px;left:12px;width:130px}.fmp-coord{top:90px;right:12px}.fmp-title{top:12px;right:12px}.fmp-north{top:12px;left:12px}}
@media(max-width:600px){.farm-map-pro{min-height:690px}.fmp-svg{inset:105px 3% 270px 3%;width:94%;height:calc(100% - 375px)}.fmp-live,.fmp-detail{width:calc(100% - 24px);left:12px;right:12px}.fmp-detail{bottom:12px}.fmp-live{bottom:175px}.fmp-legend{bottom:auto;top:108px;left:10px;width:112px}.fmp-coord{top:108px;right:10px;font-size:8px}.fmp-title b{font-size:12px}.fmp-title span{font-size:8px}.fmp-label .big{font-size:13px}.fmp-label .small{font-size:8px}.fmp-label .area{font-size:11px}}
`;
document.head.appendChild(st)}
function liveValues(){const d=state();const crops=Array.isArray(d.crops)?d.crops:[];const wheat=crops.find(c=>String(c.name||'').includes('قمح'));const alf=crops.find(c=>String(c.name||'').includes('برسيم'));return{total:n(d.totalLand||200),prepared:n(d.preparedLand||140),wheat:n(d.wheatArea||wheat?.area||50),alf:n(d.alfalfaArea||alf?.area||50),well:n(d.wellFlow||200),hours:n(d.wellHours||7),solar:n(d.solarKW||110),energy:n(d.energyCoverage||60)}}
function svgPlan(v){return `<svg class="fmp-svg" viewBox="0 0 760 1080" role="img" aria-label="مخطط تفاعلي لمزرعة تنيدة">
<polygon class="fmp-land" points="185,45 505,150 665,760 475,1030 125,850 95,175"/>
<polygon class="fmp-sector fmp-wheat" data-sector="wheat" points="185,45 505,150 470,420 145,330"/>
<polygon class="fmp-sector fmp-service" data-sector="service" points="145,330 470,420 448,485 137,395"/>
<polygon class="fmp-sector fmp-alfalfa" data-sector="alfalfa" points="137,395 448,485 410,700 110,615"/>
<polygon class="fmp-sector fmp-expand" data-sector="expand" points="410,700 575,755 475,1030 330,955"/>
<polygon class="fmp-sector fmp-water" data-sector="water" points="110,615 250,655 225,785 125,850"/>
<polygon class="fmp-sector fmp-power" data-sector="power" points="250,655 410,700 375,830 225,785"/>
<path class="fmp-road" d="M270 35 L315 1010 L350 1025 L320 35 Z"/>
<path class="fmp-road2" d="M115 610 L430 700"/><path class="fmp-road2" d="M115 610 L430 700"/>
<text class="fmp-label" x="330" y="190"><tspan class="big" x="330">القطاع الشمالي</tspan><tspan class="area" x="330" dy="25">${fmt(v.wheat)} فدان</tspan><tspan class="small" x="330" dy="20">قمح موسمي</tspan></text>
<text class="fmp-label" x="300" y="365"><tspan class="big" x="300">ممر خدمة</tspan><tspan class="small" x="300" dy="20">طرق وممرات تشغيلية</tspan></text>
<text class="fmp-label" x="285" y="540"><tspan class="big" x="285">القطاع الأوسط</tspan><tspan class="area" x="285" dy="25">${fmt(v.alf)} فدان</tspan><tspan class="small" x="285" dy="20">برسيم حجازي</tspan></text>
<text class="fmp-label dark" x="470" y="825"><tspan class="big" x="470">قطاع التوسع</tspan><tspan class="small" x="470" dy="20">أرض متاحة للاستثمار</tspan></text>
<text class="fmp-label dark" x="170" y="705"><tspan class="big" x="170">بئر المياه</tspan><tspan class="small" x="170" dy="20">مصدر المياه</tspan></text>
<text class="fmp-label dark" x="315" y="750"><tspan class="big" x="315">الري والطاقة</tspan><tspan class="small" x="315" dy="20">شمسي / كهرباء</tspan></text>
<circle class="fmp-point" data-point="well" cx="175" cy="700" r="17"/><circle class="fmp-point-core" cx="175" cy="700" r="6"/>
<circle class="fmp-point" data-point="power" cx="320" cy="760" r="17"/><circle class="fmp-point-core" cx="320" cy="760" r="6"/>
<circle class="fmp-point" data-point="site" cx="475" cy="930" r="17"/><circle class="fmp-point-core" cx="475" cy="930" r="6"/>
<text class="fmp-point-text" x="475" y="965">الموقع الحقيقي</text>
</svg>`}
function render(){const old=$('#fvi-fields .fvi-map');if(!old)return;if(old.dataset.pro==='11')return;old.dataset.pro='11';old.className='farm-map-pro';const v=liveValues();const maps=`https://www.google.com/maps?q=${FARM_LOCATION.lat},${FARM_LOCATION.lng}`;old.innerHTML=`<div class="fmp-bg"></div><div class="fmp-grid"></div><div class="fmp-title"><b>مخطط مزرعة تنيدة</b><span>200 فدان — خريطة تشغيلية تفاعلية</span></div><div class="fmp-north"><div class="arrow"></div><small>شمال</small></div><div class="fmp-coord">${FARM_LOCATION.latDms}<br>${FARM_LOCATION.lngDms}<a href="${maps}" target="_blank" rel="noopener">فتح الموقع في Google Maps ↗</a></div><div class="fmp-legend"><h5>دليل الخريطة</h5><div class="fmp-legend-row"><i class="fmp-swatch sw-wheat"></i>قمح</div><div class="fmp-legend-row"><i class="fmp-swatch sw-alf"></i>برسيم حجازي</div><div class="fmp-legend-row"><i class="fmp-swatch sw-exp"></i>توسع زراعي</div><div class="fmp-legend-row"><i class="fmp-swatch sw-serv"></i>خدمات وممرات</div><div class="fmp-legend-row"><i class="fmp-swatch sw-water"></i>مياه</div><div class="fmp-legend-row"><i class="fmp-swatch sw-power"></i>طاقة</div></div>${svgPlan(v)}<div class="fmp-live"><h4>الحالة الحالية — متغيرة من بيانات الموقع</h4><div class="fmp-live-grid"><div class="fmp-live-item"><span>إجمالي الأرض</span><b>${fmt(v.total)} فدان</b></div><div class="fmp-live-item"><span>الأرض المجهزة</span><b>${fmt(v.prepared)} فدان</b></div><div class="fmp-live-item"><span>قمح</span><b>${fmt(v.wheat)} فدان</b></div><div class="fmp-live-item"><span>برسيم حجازي</span><b>${fmt(v.alf)} فدان</b></div></div><div class="fmp-live-note">هذه الأرقام تُقرأ من حالة الموقع الحالية؛ لا توجد أرقام ثابتة داخل الرسم.</div></div><div class="fmp-detail"><h4 id="fmpDetailTitle">اختر قطاعًا أو أصلًا على الخريطة</h4><p id="fmpDetailText">اضغط على أي جزء من المخطط لعرض بياناته ومصدرها وحالتها الحالية.</p><div class="fmp-detail-grid" id="fmpDetailGrid"></div><a class="fmp-btn" href="#water" onclick="document.querySelector('[data-tab=water]')?.click();return true">الانتقال إلى المياه والطاقة</a></div>`;
function detail(title,text,items){$('#fmpDetailTitle',old).textContent=title;$('#fmpDetailText',old).textContent=text;$('#fmpDetailGrid',old).innerHTML=items.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
old.querySelectorAll('.fmp-sector').forEach(el=>el.addEventListener('click',()=>{old.querySelectorAll('.fmp-sector').forEach(x=>x.classList.remove('active'));el.classList.add('active');const v=liveValues();const map={wheat:['القطاع الشمالي','القمح الموسمي — بيانات المساحة مرتبطة بخطة الحقول. [[' ,'المساحة',fmt(v.wheat)+' فدان'],['الحالة','زراعة حالية'],['المصدر','خطة الحقول / بيانات الموقع']],alfalfa:['القطاع الأوسط','البرسيم الحجازي — المساحة الحالية تُقرأ من بيانات الحقول. [[' ,'المساحة',fmt(v.alf)+' فدان'],['الحالة','زراعة حالية'],['المصدر','خطة الحقول / بيانات الموقع']],expand:['قطاع التوسع','هذه مساحة تخطيطية للتوسع وليست قيمة نهائية؛ تحدد بعد مراجعة المياه والجدوى.',['المساحة المتاحة','تحدد من خطة الاستثمار'],['الحالة','متاحة للدراسة'],['المصدر','خطة الاستثمار']],service:['منطقة الخدمات','ممرات وخدمات تشغيلية؛ الرسم تخطيطي ولا يمثل مسحًا هندسيًا.',['الاستخدام','خدمات وممرات'],['الحالة','تشغيلي'],['المصدر','مخطط التنفيذ']],};const m=map[el.dataset.sector];if(m)detail(m[0],m[1],m.slice(2));}));
old.querySelectorAll('.fmp-point').forEach(el=>el.addEventListener('click',()=>{const v=liveValues();if(el.dataset.point==='well')detail('البئر الرئيسي','مصدر المياه للمزرعة. تفاصيل التصرف وساعات التشغيل تأتي من بيانات المياه والطاقة.',['التصرف',fmt(v.well)+' م³/ساعة'],['التشغيل',fmt(v.hours)+' ساعة/يوم'],['المصدر','المياه والطاقة']]);else if(el.dataset.point==='power')detail('الري والطاقة','منظومة الطاقة التي تغذي تشغيل الضخ والري وفق مدخلات الموقع.',['الطاقة الشمسية',fmt(v.solar)+' kW'],['كفاية الطاقة',fmt(v.energy)+'%'],['المصدر','المياه والطاقة']]);else detail('موقع مزرعة تنيدة الحقيقي','الإحداثيات مأخوذة من الموقع الذي حدده المستخدم. حدود الأرض الداخلية في الرسم تخطيطية.',['خط العرض',FARM_LOCATION.latDms],['خط الطول',FARM_LOCATION.lngDms],['المصدر','إحداثيات الموقع']]);}));}
function boot(){inject();render();setTimeout(()=>{if($('#fvi-fields .fvi-map')?.dataset.pro!=='11')render()},700);setTimeout(()=>{if($('#fvi-fields .fvi-map')?.dataset.pro!=='11')render()},1800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.FarmMapPro={boot,render,location:FARM_LOCATION};
})();
