/* V12.3 — Tanida Farm: one authoritative site map + no duplicate map on fields */
(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s);
const FARM={lat:25.4026389,lng:29.4066667};
const read=()=>{try{return JSON.parse(localStorage.getItem('tanida_dashboard_v2')||'{}')}catch(e){return {}}};
const num=v=>Number(v||0); const fmt=v=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(num(v));
function values(){const d=read(), crops=Array.isArray(d.crops)?d.crops:[]; const w=crops.find(x=>String(x.name||'').includes('قمح')); const a=crops.find(x=>String(x.name||'').includes('برسيم')); return {wheat:num(d.wheatArea||w?.area||50),alf:num(d.alfalfaArea||a?.area||50),well:num(d.wellFlow||200),hours:num(d.wellHours||7),solar:num(d.solarKW||110),energy:num(d.energyCoverage||60)};}
function onFieldsPage(){return (location.hash||'').toLowerCase()==='#fields';}
function hideLegacy(){document.querySelectorAll('#fields .map-shell,#fields .map-ui,#fields .map-head,#fields .map-legend,#fields .map-canvas').forEach(el=>{if(!el.closest('.farm-map-v12'))el.style.display='none';});}
function removeDuplicateFieldsVisual(){if(!onFieldsPage())return;document.querySelectorAll('#fvi-fields').forEach(el=>el.remove());}
function style(){if($('#tanidaMapV123Style'))return;const s=document.createElement('style');s.id='tanidaMapV123Style';s.textContent=`
#fields .map-shell,#fields .map-ui,#fields .map-head,#fields .map-legend,#fields .map-canvas{display:none!important}
.map-shell .map-head{display:none!important}
.farm-map-v12{position:relative;background:#d9bd8b;border:1px solid #d7ded9;border-radius:22px;overflow:hidden;box-shadow:0 12px 30px #173f2a18;font-family:Cairo,Tahoma,sans-serif;direction:rtl}
.farm-map-v12 .map-image{display:block;width:100%;height:auto;max-height:850px;object-fit:contain;background:#d9bd8b}
.farm-map-v12 .map-actions{position:absolute;left:16px;top:16px;z-index:8;display:flex;gap:6px;flex-wrap:wrap}
.farm-map-v12 .map-actions a,.farm-map-v12 .map-actions button{border:0;border-radius:10px;background:#0f7659;color:#fff;padding:7px 10px;font:700 10px Cairo;cursor:pointer;text-decoration:none}
.farm-map-v12 .map-hotspot{position:absolute;z-index:6;border:2px solid transparent;background:transparent;border-radius:18px;cursor:pointer}
.farm-map-v12 .map-hotspot:hover,.farm-map-v12 .map-hotspot.active{border-color:#0f7659;background:#0f76591c;box-shadow:0 0 0 4px #fff8}
.farm-map-v12 .map-detail{position:absolute;left:16px;bottom:16px;z-index:10;width:290px;background:#fffffff5;border:1px solid #d7e0da;border-radius:16px;padding:13px;box-shadow:0 10px 28px #0003;display:none}
.farm-map-v12 .map-detail.show{display:block}
.farm-map-v12 .map-detail h4{margin:0 0 5px;color:#174b3a;font-size:14px}
.farm-map-v12 .map-detail p{margin:0 0 8px;color:#637168;font-size:10px;line-height:1.8}
.farm-map-v12 .map-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}
.farm-map-v12 .map-detail-grid div{background:#f3f7f4;border-radius:9px;padding:7px}
.farm-map-v12 .map-detail-grid span{display:block;font-size:8px;color:#77827c}
.farm-map-v12 .map-detail-grid b{display:block;font-size:13px;color:#174b3a}
.farm-map-v12 .map-close{position:absolute;left:8px;top:7px;border:0;background:transparent;color:#66736c;font-size:16px;cursor:pointer}
.farm-map-v12 .map-status{font-size:9px;color:#6b7871;margin-top:8px}.farm-map-v12 .map-status strong{color:#0f7659}
@media(max-width:700px){.farm-map-v12 .map-actions{left:10px;top:10px}.farm-map-v12 .map-actions a,.farm-map-v12 .map-actions button{font-size:8px;padding:6px 8px}.farm-map-v12 .map-detail{left:10px;right:10px;bottom:10px;width:auto}}
`;document.head.appendChild(s)}
function detail(kind){const v=values();return {wheat:{title:'القطاع الشمالي — القمح',desc:'بيانات القطاع مرتبطة بحالة المزرعة الحالية.',items:[['المساحة',fmt(v.wheat)+' فدان'],['الحالة','زراعة حالية']]},alf:{title:'القطاع الأوسط — البرسيم الحجازي',desc:'بيانات القطاع مرتبطة بحالة المزرعة الحالية.',items:[['المساحة',fmt(v.alf)+' فدان'],['الحالة','زراعة حالية']]},palm1:{title:'نخيل مجدول — المنطقة الأولى',desc:'منطقة النخيل المجدول كما هي محددة في المخطط الأصلي.',items:[['المحصول','نخيل مجدول'],['المصدر','المخطط المعتمد']]},palm2:{title:'نخيل مجدول — المنطقة الثانية',desc:'منطقة النخيل المجدول كما هي محددة في المخطط الأصلي.',items:[['المحصول','نخيل مجدول'],['المصدر','المخطط المعتمد']]},well:{title:'البئر الرئيسي',desc:'بيانات المياه المستخدمة في تقديرات التشغيل.',items:[['التصرف',fmt(v.well)+' م³/ساعة'],['ساعات التشغيل',fmt(v.hours)+' ساعة/يوم']]},power:{title:'الطاقة',desc:'بيانات الطاقة المستخدمة في تقديرات التشغيل.',items:[['الطاقة الشمسية',fmt(v.solar)+' kW'],['كفاية الطاقة',fmt(v.energy)+'%']]}}[kind]||null;}
function render(){removeDuplicateFieldsVisual();if(onFieldsPage())return;hideLegacy();const host=$('#fvi-fields .fvi-map');if(!host)return;if(host.dataset.v123==='1')return;host.dataset.v123='1';style();hideLegacy();host.className='farm-map-v12';const mapUrl=`https://www.google.com/maps?q=${FARM.lat},${FARM.lng}`;host.innerHTML=`<img class="map-image" src="farm-site-plan.svg?v=20260821-1" alt="المخطط الفعلي لمزرعة تنيدة — الحدود بين النقاط 4 و200.1 و200.2 و1"><div class="map-actions"><a href="${mapUrl}" target="_blank" rel="noopener">فتح الموقع في Google Maps ↗</a><button type="button" data-reset>إغلاق التفاصيل</button></div><button class="map-hotspot" data-kind="wheat" style="right:31%;top:13%;width:38%;height:25%" aria-label="القمح"></button><button class="map-hotspot" data-kind="palm1" style="right:48%;top:34%;width:24%;height:9%" aria-label="نخيل مجدول المنطقة الأولى"></button><button class="map-hotspot" data-kind="alf" style="right:31%;top:42%;width:38%;height:28%" aria-label="البرسيم الحجازي"></button><button class="map-hotspot" data-kind="well" style="right:42%;top:56%;width:16%;height:14%" aria-label="البئر"></button><button class="map-hotspot" data-kind="palm2" style="right:31%;top:70%;width:24%;height:9%" aria-label="نخيل مجدول المنطقة الثانية"></button><button class="map-hotspot" data-kind="power" style="right:48%;top:78%;width:22%;height:14%" aria-label="الطاقة"></button><div class="map-detail" id="tanidaMapDetail"><button class="map-close" type="button" data-close>×</button><h4 id="mapDetailTitle"></h4><p id="mapDetailDesc"></p><div class="map-detail-grid" id="mapDetailGrid"></div><div class="map-status">المصدر: <strong>بيانات حالة الموقع الحالية / المخطط الأصلي</strong></div></div>`;const detailBox=$('#tanidaMapDetail',host);function open(k){const d=detail(k);if(!d)return;$('#mapDetailTitle',host).textContent=d.title;$('#mapDetailDesc',host).textContent=d.desc;$('#mapDetailGrid',host).innerHTML=d.items.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');detailBox.classList.add('show');host.querySelectorAll('.map-hotspot').forEach(x=>x.classList.toggle('active',x.dataset.kind===k));}host.querySelectorAll('.map-hotspot').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();open(b.dataset.kind)}));$('[data-close]',host).addEventListener('click',()=>{detailBox.classList.remove('show');host.querySelectorAll('.map-hotspot').forEach(x=>x.classList.remove('active'))});$('[data-reset]',host).addEventListener('click',()=>{$('[data-close]',host).click()});}
function boot(){let tries=0;const t=setInterval(()=>{removeDuplicateFieldsVisual();render();if(onFieldsPage()||$('#fvi-fields .fvi-map')||++tries>30)clearInterval(t)},500);const obs=new MutationObserver(()=>{removeDuplicateFieldsVisual();hideLegacy();});obs.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();