/* V12.0 — Tanida Farm: corrected site plan + live interactive details */
(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s);
const FARM={lat:25.4026389,lng:29.4066667,latDms:'25°24\'09.5"N',lngDms:'29°24\'24.0"E'};
const read=()=>{try{return JSON.parse(localStorage.getItem('tanida_dashboard_v2')||'{}')}catch(e){return {}}};
const num=v=>Number(v||0); const fmt=v=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(num(v));
function values(){const d=read(), crops=Array.isArray(d.crops)?d.crops:[]; const w=crops.find(x=>String(x.name||'').includes('قمح')); const a=crops.find(x=>String(x.name||'').includes('برسيم')); return {total:num(d.totalLand||200),prepared:num(d.preparedLand||140),wheat:num(d.wheatArea||w?.area||50),alf:num(d.alfalfaArea||a?.area||50),well:num(d.wellFlow||200),hours:num(d.wellHours||7),solar:num(d.solarKW||110),energy:num(d.energyCoverage||60)};}
function style(){if($('#tanidaMapV12Style'))return;const s=document.createElement('style');s.id='tanidaMapV12Style';s.textContent=`
.farm-map-v12{position:relative;background:#d9bd8b;border:1px solid #d7ded9;border-radius:22px;overflow:hidden;box-shadow:0 12px 30px #173f2a18;font-family:Cairo,Tahoma,sans-serif;direction:rtl}.farm-map-v12 .map-image{display:block;width:100%;height:auto;max-height:850px;object-fit:contain;background:#d9bd8b}.map-head{position:absolute;top:16px;right:16px;z-index:8;background:#fffffff2;border:1px solid #d6dfd9;border-radius:14px;padding:9px 14px;box-shadow:0 5px 16px #0002;color:#174b3a}.map-head b{display:block;font-size:16px}.map-head span{font-size:10px;color:#68756e}.map-actions{position:absolute;left:16px;top:16px;z-index:8;display:flex;gap:6px;flex-wrap:wrap}.map-actions a,.map-actions button{border:0;border-radius:10px;background:#0f7659;color:#fff;padding:7px 10px;font:700 10px Cairo;cursor:pointer;text-decoration:none}.map-note{position:absolute;right:16px;bottom:16px;z-index:8;background:#fffffff0;border-radius:12px;padding:8px 11px;color:#3e5047;font-size:9px;box-shadow:0 5px 16px #0002}.map-hotspot{position:absolute;z-index:6;border:2px solid transparent;background:transparent;border-radius:18px;cursor:pointer}.map-hotspot:hover,.map-hotspot.active{border-color:#0f7659;background:#0f76591c;box-shadow:0 0 0 4px #fff8}.map-detail{position:absolute;left:16px;bottom:16px;z-index:10;width:290px;background:#fffffff5;border:1px solid #d7e0da;border-radius:16px;padding:13px;box-shadow:0 10px 28px #0003;display:none}.map-detail.show{display:block}.map-detail h4{margin:0 0 5px;color:#174b3a;font-size:14px}.map-detail p{margin:0 0 8px;color:#637168;font-size:10px;line-height:1.8}.map-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.map-detail-grid div{background:#f3f7f4;border-radius:9px;padding:7px}.map-detail-grid span{display:block;font-size:8px;color:#77827c}.map-detail-grid b{display:block;font-size:13px;color:#174b3a}.map-close{position:absolute;left:8px;top:7px;border:0;background:transparent;color:#66736c;font-size:16px;cursor:pointer}.map-status{font-size:9px;color:#6b7871;margin-top:8px}.map-status strong{color:#0f7659}@media(max-width:700px){.farm-map-v12{min-height:520px}.map-head{top:10px;right:10px}.map-head b{font-size:12px}.map-head span{font-size:8px}.map-actions{left:10px;top:10px}.map-actions a,.map-actions button{font-size:8px;padding:6px 8px}.map-detail{left:10px;right:10px;bottom:10px;width:auto}.map-note{right:10px;bottom:10px;font-size:8px}.map-detail.show{bottom:10px}.map-note.detail-open{display:none}}
`;document.head.appendChild(s)}
function detail(kind){const v=values();const data={wheat:{title:'القطاع الشمالي — القمح',desc:'بيانات القطاع مرتبطة بحالة المزرعة الحالية.',items:[['المساحة',fmt(v.wheat)+' فدان'],['الحالة','زراعة حالية']]},alf:{title:'القطاع الأوسط — البرسيم الحجازي',desc:'بيانات القطاع مرتبطة بحالة المزرعة الحالية.',items:[['المساحة',fmt(v.alf)+' فدان'],['الحالة','زراعة حالية']]},well:{title:'البئر الرئيسي',desc:'بيانات المياه المستخدمة في تقديرات التشغيل.',items:[['التصرف',fmt(v.well)+' م³/ساعة'],['ساعات التشغيل',fmt(v.hours)+' ساعة/يوم']]},power:{title:'الطاقة',desc:'بيانات الطاقة المستخدمة في تقديرات التشغيل.',items:[['الطاقة الشمسية',fmt(v.solar)+' kW'],['كفاية الطاقة',fmt(v.energy)+'%']]},site:{title:'حدود الموقع',desc:'الحدود الفعلية للمزرعة هي المنطقة المحصورة بين النقاط 1 و2 و3 و4 فقط.',items:[['الحالة','حدود الموقع الفعلية'],['التوسع خارج الحدود','غير معتمد']]}};return data[kind]||null;}
function render(){const host=$('#fvi-fields .fvi-map');if(!host)return;if(host.dataset.v12==='1')return;host.dataset.v12='1';style();const v=values();host.className='farm-map-v12';const mapUrl=`https://www.google.com/maps?q=${FARM.lat},${FARM.lng}`;host.innerHTML=`<img class="map-image" src="farm-site-plan.svg?v=12" alt="المخطط الاحترافي لمزرعة تنيدة — الحدود الفعلية بين النقاط 1 و2 و3 و4"><div class="map-head"><b>مخطط مزرعة تنيدة</b><span>الموقع والتنفيذ — المخطط الفعلي بين النقاط 1 و4</span></div><div class="map-actions"><a href="${mapUrl}" target="_blank" rel="noopener">فتح الموقع في Google Maps ↗</a><button type="button" data-reset>إغلاق التفاصيل</button></div><button class="map-hotspot" data-kind="wheat" style="right:36%;top:18%;width:34%;height:23%" aria-label="القطاع الشمالي"></button><button class="map-hotspot" data-kind="alf" style="right:40%;top:32%;width:34%;height:28%" aria-label="القطاع الأوسط"></button><button class="map-hotspot" data-kind="well" style="right:62%;top:53%;width:12%;height:15%" aria-label="البئر"></button><button class="map-hotspot" data-kind="power" style="right:43%;top:56%;width:17%;height:15%" aria-label="الخدمات"></button><button class="map-hotspot" data-kind="site" style="right:5%;top:5%;width:90%;height:92%" aria-label="حدود الموقع"></button><div class="map-detail" id="tanidaMapDetail"><button class="map-close" type="button" data-close>×</button><h4 id="mapDetailTitle"></h4><p id="mapDetailDesc"></p><div class="map-detail-grid" id="mapDetailGrid"></div><div class="map-status">المصدر: <strong>بيانات حالة الموقع الحالية</strong></div></div><div class="map-note">الحدود الفعلية: النقاط 1–2–3–4 فقط</div>`;
const detailBox=$('#tanidaMapDetail',host), note=$('.map-note',host);function open(k){const d=detail(k);if(!d)return;$('#mapDetailTitle',host).textContent=d.title;$('#mapDetailDesc',host).textContent=d.desc;$('#mapDetailGrid',host).innerHTML=d.items.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');detailBox.classList.add('show');note.classList.add('detail-open');host.querySelectorAll('.map-hotspot').forEach(x=>x.classList.toggle('active',x.dataset.kind===k));}host.querySelectorAll('.map-hotspot').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();open(b.dataset.kind)}));$('[data-close]',host).addEventListener('click',()=>{detailBox.classList.remove('show');note.classList.remove('detail-open');host.querySelectorAll('.map-hotspot').forEach(x=>x.classList.remove('active'))});$('[data-reset]',host).addEventListener('click',()=>{$('[data-close]',host).click()});}
function boot(){let tries=0;const t=setInterval(()=>{render();if($('#fvi-fields .fvi-map')||++tries>30)clearInterval(t)},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();